[package]
name = "core-mx-liveliness-stake-meta"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies.core-mx-liveliness-stake]
path = ".."

[dependencies.multiversx-sc-meta]
version = "0.50.5"
default-features = false
