// Code generated by the multiversx-sc build system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Upgrade:                              1
// Endpoints:                           26
// Async Callback (empty):               1
// Total number of exported functions:  29

#![no_std]

multiversx_sc_wasm_adapter::allocator!();
multiversx_sc_wasm_adapter::panic_handler!();

multiversx_sc_wasm_adapter::endpoints! {
    core_mx_liveliness_stake
    (
        init => init
        upgrade => upgrade
        claimRewards => claim_rewards
        setContractStateActive => set_contract_state_active
        setContractStateInactive => set_contract_state_inactive
        setMaxApr => set_max_apr
        setRewardsTokenIdentifier => set_rewards_token_identifier
        setPerBlockRewardAmount => set_per_block_rewards
        topUpRewards => top_up_rewards
        withdrawRewards => withdraw_rewards
        startProduceRewards => start_produce_rewards
        endProduceRewards => end_produce_rewards
        setBondContractAddress => set_bond_contract_address
        setAdministrator => set_administrator
        getContractState => contract_state
        rewardsState => rewards_state
        getAdministrator => administrator
        bondContractAddress => bond_contract_address
        rewardsReserve => rewards_reserve
        accumulatedRewards => accumulated_rewards
        rewardsTokenIdentifier => rewards_token_identifier
        rewardsPerBlock => rewards_per_block
        lastRewardBlockNonce => last_reward_block_nonce
        rewardsPerShare => rewards_per_share
        addressLastRewardPerShare => address_last_reward_per_share
        maxApr => max_apr
        claimableRewards => claimable_rewards
        contractDetails => contract_details
    )
}

multiversx_sc_wasm_adapter::async_callback_empty! {}
